channels:
  - conda-forge
  - defaults
  - astra-toolbox/label/dev
  - savu-dep
  - ccpi
  - fastai
dependencies:
  - python=3.7
  - anaconda-client
  - tomopy
  - scipy
  - numpy
  - pandas
  - PyWavelets
  - scikit-learn
  - scikit-image
  - geodistk
  - morphsnakes
  - tomobar
  - larix
  - ccpi-reconstruction
  - ccpi-regulariser
  - tomophantom
  - astra-toolbox
  - pyfai
  - pymca==5.5.5
  - pyfftw
  - xraylib
  - PeakUtils
  - mrcfile
  - tifffile
  - fabio
  - colorama
  - jinja2
  - ipython
  - pytest
  - pytest-xdist
  - setuptools
  - mock
  - spyder
  - pip
  - fastai==1.0.59
  - pip:
      - matplotlib
      - pyreadline
      - pmacparser
      - gnureadline==6.3.8
      - sphinx-rtd-theme
      - sphinx-argparse
      - nvidia-ml-py3
