name: test-environment
channels:
  - astra-toolbox
  - dgursoy
  - conda-forge
  - anaconda
dependencies:
  - python==2.7
  - numpy
  - scipy
  - pytest
  - h5py
  - pep8
  - mpi4py 
  - scikit-image==0.14.0
  - astra-toolbox
  - xraylib
  - tomopy
  - mock
  - fabio==0.4.0
  - pytest-cov
  - coveralls
  - pyfai 
  - pyfftw
  - colorama
  - pymca
  - pip:
    - nvidia-ml-py
    - peakutils
    - gnureadline
    - pmacparser

