name: test-environment
channels:
  - soft-matter # for pyfftw
  - astra-toolbox
  - tacaswell
  - dgursoy
dependencies:
  - python=2.7
  - numpy
  - scipy
  - pyfftw
  - pytest
  - h5py
  - pep8
  - pytest
  - mpi4py 
  - scikit-image
  - astra-toolbox
  - xraylib
  - tomopy
  - pip:
    - fabio 
    - pytest-cov
    - coveralls
    - pyFAI 
    - nvidia-ml-py
    - pyfftw
    - peakutils
    - "--editable=git+https://github.com/aaron-parsons/pymca"
    - colorama

