# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1

orbs:
  singularity: singularity/singularity@1.0.4

workflows:
  version: 2
  savu:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
#            branches:
#              only: master
          name: "Singularity 2.6.1 - Python 3"
          singularity: 2.6.1
          singularity-3: false


jobs:
  build:
    parameters:
        singularity:
          type: string
          description: "Singularity version"
        singularity-3:
          type: boolean
          description: "Set to true for singularity 3, false for singularity 2"
          default: true
    machine: true
    working_directory: ~/repo
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v7-dependencies

      - run:
          name: install dependencies
          command: | 
            ls $HOME
            if [ ! -d "/home/circleci/conda" ]; then
                wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
                /bin/bash Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/conda
                export PATH=$HOME/conda/bin:$PATH
                conda install -y -c defaults -c conda-forge sregistry-google-storage
            else
                echo "Miniconda is already installed, continuing to build."
            fi

      # Install Singularity
      - when:
          condition: << parameters.singularity-3 >>
          steps:
            - singularity/install-go:
                go-version: 1.11.5
            - singularity/debian-install-3:
                      singularity-version: << parameters.singularity >>
      - unless:
          condition: << parameters.singularity-3 >>
          steps:
            - singularity/debian-install-2:
                      singularity-version: << parameters.singularity >>

      - save_cache:
          paths:
            - /home/circleci/conda
          key: v7-dependencies
        
      - run:
          name: build Savu images
          command: |
            cd ~/repo/singularity-recipes
            export PATH=$HOME/conda/bin:$PATH
            python mass-rebuild.py
          no_output_timeout: 60m
