name: root
channels:
- defaults
dependencies:
- scipy==1.1.0
- colorama==0.3.9
- setuptools==39.2.0
- jinja2==2.10
- numpy==1.14.5
- pandas==0.23.3
- mock==2.0.0
- PyWavelets==0.5.2
- scikit-image==0.14.0
- scikit-learn==0.19.1
- pytest==3.6.2
- spyder==3.3.0
- ipython==5.7.0
- cython==0.28.3
- pip:
  - fabio==0.4.0
  - pyfftw==0.10.4
  - nvidia-ml-py==7.352.0
  - PeakUtils==1.1.1
  - pymca==5.3.1
  - tifffile==0.4.0
  - pyreadline==2.1
  - gnureadline==6.3.8
  - sphinx_rtd_theme==0.4.1

