name: root
channels:
- ccpi
- local
- conda-forge
- dgursoy
- defaults
dependencies:
- bzip2
- cairo
- fontconfig
- freetype
- gettext
- glib
- icu
- libnetcdf
- libpng
- matplotlib
- netcdf4
- pillow
- pyfftw
- qt
- alabaster
- asn1crypto
- astroid
- babel
- backports
- backports_abc
- beautifulsoup4
- bleach
- cffi
- chardet
- colorama
- conda
- conda-build
- conda-env
- conda-verify
- configparser
- contextlib2
- cryptography
- curl
- cycler
- cython
- dbus
- decorator
- docutils
- entrypoints
- enum34
- expat
- filelock
- funcsigs
- functools32
- futures
- get_terminal_size
- glob2
- gst-plugins-base
- gstreamer
- html5lib
- idna
- imagesize
- ipaddress
- ipykernel
- ipython
- ipython_genutils
- isort
- jbig
- jedi
- jinja2
- jpeg
- jsonschema
- jupyter_client
- jupyter_core
- lazy-object-proxy
- libffi
- libgcc
- libgfortran
- libiconv
- libsodium
- libtiff
- libxcb
- libxml2
- markupsafe
- mistune
- mkl
- mock
- mpmath
- nbconvert
- nbformat
- networkx
- numexpr
- numpy
- numpydoc
- olefile
- openssl
- packaging
- pandas
- pandocfilters
- patchelf
- path.py
- pathlib2
- pbr
- pcre
- pep8
- pexpect
- pickleshare
- pip
- pixman
- pkginfo
- prompt_toolkit
- psutil
- ptyprocess
- py
- pycairo
- pycosat
- pycparser
- pycrypto
- pyflakes
- pygments
- pylint
- pyopenssl
- pyparsing
- pyqt
- pytest
- python
- python-dateutil
- pytz
- pyyaml
- pyzmq
- qtawesome
- qtconsole
- qtpy
- readline
- requests
- rope
- ruamel_yaml
- scandir
- scikit-image
- scikit-learn
- scipy
- setuptools
- simplegeneric
- singledispatch
- sip
- six
- snowballstemmer
- sphinx
- sphinxcontrib
- sphinxcontrib-websupport
- spyder
- sqlite
- ssl_match_hostname
- subprocess32
- sympy
- testpath
- tk
- tornado
- traitlets
- typing
- wcwidth
- wheel
- wrapt
- xz
- yaml
- zeromq
- zlib
- dxchange
- dxfile
- edffile
- fftw
- pywavelets
- spefile
- tifffile
- pip:
  - appdirs
  - backports-abc
  - backports.shutil-get-terminal-size
  - backports.ssl-match-hostname
  - cached-property
  - fabio
  - fisx
  - ipython-genutils
  - ipywidgets
  - jupyter
  - jupyter-client
  - jupyter-console
  - jupyter-core
  - lmfit
  - mako
  - mrcfile
  - notebook
  - nvidia-ml-py
  - peakutils
  - phasepack
  - polytope
  - prompt-toolkit
  - pyfai
  - pymca
  - pymca5
  - pyreadline
  - pytools
  - readme-renderer
  - restview
  - simpleitk
  - sphinx-rtd-theme
  - terminado
  - webencodings
  - widgetsnbextension

