name: root
channels:
  - tom.schoonjans
  - local
  - conda-forge
  - defaults
dependencies:
  - alabaster=0.7.10=py27_1
  - asn1crypto=0.24.0=py27_0
  - astroid=1.6.3=py27_0
  - attrs=18.1.0=py_0
  - babel=2.5.3=py27_0
  - backports=1.0=py27_1
  - backports.functools_lru_cache=1.5=py27_0
  - backports.lzma=0.0.10=py27_0
  - backports.shutil_get_terminal_size=1.0.0=py_3
  - backports_abc=0.5=py27_0
  - beautifulsoup4=4.6.0=py27_0
  - bleach=2.1.3=py_0
  - bzip2=1.0.6=1
  - ca-certificates=2018.4.16=0
  - cairo=1.14.10=0
  - certifi=2018.4.16=py27_0
  - cffi=1.11.5=py27_0
  - cftime=1.0.0b1=py27_0
  - chardet=3.0.4=py27_0
  - cloudpickle=0.5.3=py_0
  - colorama=0.3.9=py27_0
  - conda=4.5.3=py27_0
  - conda-build=3.10.2=py27_0
  - conda-env=2.6.0=0
  - conda-verify=2.0.0=py27_0
  - configparser=3.5.0=py27_0
  - contextlib2=0.5.5=py27_1
  - cryptography=2.2.1=py27_0
  - curl=7.59.0=1
  - cycler=0.10.0=py27_0
  - cython=0.28.2=py27_0
  - dask-core=0.17.4=py_0
  - dbus=1.11.0=0
  - decorator=4.3.0=py_0
  - docutils=0.14=py27_0
  - edffile=5.0.0=py27_0
  - entrypoints=0.2.3=py27_1
  - enum34=1.1.6=py27_1
  - expat=2.2.5=0
  - fastcache=1.0.2=py27_0
  - fftw=3.3.7=0
  - filelock=3.0.4=py27_0
  - fontconfig=2.12.6=0
  - freetype=2.8.1=0
  - funcsigs=1.0.2=py_2
  - functools32=3.2.3.2=py27_2
  - futures=3.2.0=py27_0
  - gettext=0.19.8.1=0
  - glib=2.55.0=0
  - glob2=0.5=py27_0
  - gmp=6.1.2=0
  - gmpy2=2.0.8=py27_0
  - gst-plugins-base=1.8.0=0
  - gstreamer=1.8.0=1
  - hdf4=4.2.13=0
  - html5lib=1.0.1=py_0
  - icu=58.2=0
  - idna=2.6=py27_1
  - imageio=2.3.0=py27_0
  - imagesize=1.0.0=py27_0
  - ipaddress=1.0.22=py_1
  - ipykernel=4.8.2=py27_0
  - ipython=5.7.0=py27_0
  - ipython_genutils=0.2.0=py27_0
  - isort=4.3.4=py27_0
  - jbig=2.1=0
  - jedi=0.12.0=py27_0
  - jinja2=2.10=py27_0
  - jpeg=9b=2
  - jsonschema=2.6.0=py27_1
  - jupyter_client=5.2.3=py27_0
  - jupyter_core=4.4.0=py_0
  - kiwisolver=1.0.1=py27_1
  - krb5=1.14.6=0
  - lazy-object-proxy=1.3.1=py27_0
  - libedit=3.1.20170329=0
  - libffi=3.2.1=3
  - libiconv=1.15=0
  - libpng=1.6.34=0
  - libsodium=1.0.16=0
  - libssh2=1.8.0=2
  - libtiff=4.0.9=0
  - libxcb=1.13=0
  - libxml2=2.9.8=0
  - linecache2=1.0.0=py27_0
  - mako=1.0.7=py27_0
  - markupsafe=1.0=py27_0
  - matplotlib=2.2.2=py27_1
  - mccabe=0.6.1=py27_0
  - mistune=0.8.3=py27_1
  - mock=2.0.0=py27_0
  - more-itertools=4.1.0=py_0
  - mpc=1.1.0=5
  - mpfr=4.0.1=0
  - mpmath=1.0.0=py_0
  - nbconvert=5.3.1=py_1
  - nbformat=4.4.0=py27_0
  - ncurses=5.9=10
  - networkx=2.1=py27_0
  - numexpr=2.6.5=py27_0
  - numpydoc=0.8.0=py27_0
  - olefile=0.45.1=py27_0
  - openblas=0.2.20=7
  - openssl=1.0.2o=0
  - packaging=17.1=py_0
  - pandas=0.23.0=py27_0
  - pandoc=2.2.1=0
  - pandocfilters=1.4.2=py27_0
  - parso=0.2.0=py_0
  - patchelf=0.9=2
  - path.py=10.3.1=py27_0
  - pathlib2=2.3.2=py27_0
  - pbr=4.0.2=py_0
  - pcre=8.41=1
  - pep8=1.7.1=py_0
  - pexpect=4.5.0=py27_0
  - pickleshare=0.7.4=py27_0
  - pillow=5.1.0=py27_0
  - pip=9.0.3=py27_0
  - pixman=0.34.0=2
  - pkginfo=1.4.2=py27_0
  - pluggy=0.6.0=py_0
  - prompt_toolkit=1.0.15=py27_0
  - psutil=5.4.5=py27_0
  - ptyprocess=0.5.2=py27_0
  - py=1.5.3=py_0
  - pycairo=1.16.3=py27_0
  - pycodestyle=2.4.0=py27_0
  - pycosat=0.6.3=py27_0
  - pycparser=2.18=py27_0
  - pycrypto=2.6.1=py27_1
  - pyfftw=0.10.4=py27_3
  - pyflakes=1.6.0=py27_0
  - pygments=2.2.0=py27_0
  - pylint=1.8.4=py27_0
  - pyopenssl=17.5.0=py27_1
  - pyparsing=2.2.0=py27_0
  - pyqt=5.6.0=py27_5
  - pytest=3.5.1=py27_0
  - python=2.7.15=0
  - python-dateutil=2.7.3=py_0
  - pytz=2018.4=py_0
  - pywavelets=0.5.2=py27_1
  - pyyaml=3.12=py27_1
  - pyzmq=17.0.0=py27_4
  - qt=5.6.2=7
  - qtawesome=0.4.4=py27_0
  - qtconsole=4.3.1=py27_0
  - qtpy=1.4.2=py27h8a2030e_0
  - readline=7.0=0
  - reikna=0.6.8=py27_0
  - requests=2.18.4=py27_1
  - rope=0.10.7=py27_0
  - ruamel_yaml=0.15.37=py27h470a237_0
  - scandir=1.7=py27_0
  - scikit-image=0.13.1=py27_0
  - setuptools=39.1.0=py27_0
  - simplegeneric=0.8.1=py27_0
  - singledispatch=3.4.0.3=py27_0
  - sip=4.18=py27_1
  - six=1.11.0=py27_1
  - snowballstemmer=1.2.1=py27_0
  - spefile=1.6=py_1
  - sphinx=1.7.4=py27_0
  - sphinxcontrib-websupport=1.0.1=py27_0
  - spyder=3.2.8=py27_0
  - sqlite=3.20.1=2
  - ssl_match_hostname=3.5.0.1=py27_1
  - subprocess32=3.5.0=py27_0
  - sympy=1.1.1=py27_0
  - testpath=0.3.1=py27_0
  - tifffile=0.14.0=py27_1
  - tk=8.6.7=0
  - toolz=0.9.0=py_0
  - tornado=5.0.2=py27_0
  - traceback2=1.4.0=py27_0
  - traitlets=4.3.2=py27_0
  - typing=3.6.4=py27_0
  - unittest2=1.1.0=py_0
  - wcwidth=0.1.7=py27_0
  - webencodings=0.5=py27_0
  - wheel=0.31.0=py27_0
  - wrapt=1.10.11=py27_0
  - xorg-libxau=1.0.8=3
  - xorg-libxdmcp=1.1.2=3
  - xz=5.2.3=0
  - yaml=0.1.7=0
  - zeromq=4.2.5=1
  - zlib=1.2.11=0
  - blas=1.0=mkl
  - configobj=5.0.6=py27_0
  - get_terminal_size=1.0.0=haa9412d_0
  - intel-openmp=2018.0.0=8
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=7.2.0=hdf63c60_3
  - libgfortran=3.0.0=1
  - libgfortran-ng=7.2.0=hdf63c60_3
  - libstdcxx-ng=7.2.0=hdf63c60_3
  - mkl=2018.0.2=1
  - mkl_fft=1.0.1=py27h3010b51_0
  - mkl_random=1.0.1=py27h629b387_0
  - numpy=1.14.2=py27hdbf6ddf_1
  - pysocks=1.6.8=py27_0
  - scikit-learn=0.19.1=py27h445a80a_0
  - scipy=1.1.0=py27hfc37229_0
  - sphinxcontrib=1.0=py27h1512b58_1
  - urllib3=1.22=py27ha55213b_0
  - dreampy=0.1=py27_0
  - pip:
    - appdirs==1.4.3
    - asteval==0.9.12
    - backports.ssl-match-hostname==3.5.0.1
    - cached-property==1.4.2
    - cmarkgfm==0.4.2
    - dask==0.17.4
    - fabio==0.6.0
    - fisx==1.1.4
    - future==0.16.0
    - ipywidgets==7.2.1
    - jupyter==1.0.0
    - jupyter-console==5.2.0
    - lmfit==0.9.9
    - mrcfile==1.0.4
    - notebook==5.5.0
    - nvidia-ml-py==375.53.1
    - peakutils==1.1.1
    - phasepack==1.5
    - polytope==0.2.1
    - pyfai==0.15.0
    - pymca==5.3.1
    - pymca5==5.3.1
    - pyreadline==2.1
    - pytools==2018.4
    - readme-renderer==20.0
    - restview==2.9.0
    - send2trash==1.5.0
    - silx==0.7.0
    - simpleitk==1.1.0
    - sphinx-rtd-theme==0.3.1
    - terminado==0.8.1
    - widgetsnbextension==3.2.1

